name: Godot Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - uses: actions/checkout@v4
      - name: Import project
        run: godot --headless --editor --quit --path .
      - name: Validate project files
        run: godot --headless --path . --editor --quit
